repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the ref you want to point at
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: \.out$
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: no-commit-to-branch # Protects main/master by default
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]
        exclude: ^web/
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        types: [python]
        additional_dependencies: ['click==8.0.4']
        args: ["--extend-exclude", "topostats/plotting.py"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.5.2"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.1.0
  #   hooks:
  #     - id: prettier
  #       args: [--write] # edit files in-place
  #       additional_dependencies:
  #         - prettier
  #         - prettier-plugin-svelte
  #         - svelte

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.7.0
    hooks:
      - id: eslint
        types: [file]
        args: [--fix, --resolve-plugins-relative-to, ~/.cache/pre-commit]
        files: \.(js|ts|svelte)$
        additional_dependencies:
          - eslint
          - typescript
          - svelte
          - svelte-eslint-parser
          - eslint-plugin-svelte
          - eslint-config-prettier
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'

ci:
  autofix_prs: true
  autofix_commit_msg: '[pre-commit.ci] Fixing issues with pre-commit'
  autoupdate_schedule: weekly
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit automatically updated.'
  # skip: [] # Optionally list ids of hooks to skip on CI
